Lecture 98

In [2]:
"BASICS"


'BASICS'

Python is a general-purpose, dynamic, high-level, and interpreted programming language. 
It supports Object Oriented programming approach to develop applications. 
It is simple and easy to learn and provides lots of high-level data structures.

Python is an interpreted scripting language also. Guido Van Rossum is known as the founder of Python programming.

With its interpreted nature, Python's syntax and dynamic typing make it an ideal language for scripting and rapid application development. We don't need to use data types to declare variable because it is dynamically typed, so we can write a=10 to assign an integer value in an integer variable.

Python supports multiple programming patterns, including object-oriented, imperative, and functional or procedural programming styles.

Why learn Python?

Easy to use and Learn
Expressive Language
Interpreted Language
Object-Oriented Language
Open Source Language
Extensible: Python can be extended with modules written in C, C++, or other languages.
GUI Programming Support
Integrated: Python can easily integrate with other languages and technologies, such as C/C++, Java, and . NET.
High Demand
Big Data and Machine Learning

VARIABLES

In [4]:
a=10


In [5]:
print(a)

10


In [6]:
p = 10

In [7]:
p
a+p

10

In [14]:
type(a)
type(p)

int

In [15]:
b=1.23

In [16]:
type(b)

float

In [17]:
c = 3.122234547645342

In [18]:
type(c)

float

In [19]:
p = "Sem4"

In [20]:
type(p)

str

In [24]:
e = "This is my first datascience class"

In [23]:
f = 'This is my first datascience class'

In [25]:
type(e)

str

In [26]:
type(f)

str

In [47]:
n = True 
m = False

T and F must be capital

In [38]:
type(n)

bool

In [39]:
type(m)

bool

In [44]:
n+m

1

internally n = 1 and m = 0

In [48]:
True * True

1

In [4]:
True * False

0

In [50]:
True/False

ZeroDivisionError: division by zero

In [51]:
False/True

0.0

note - in numpy 1/0 is error but infinity and it will give

In [53]:
v = 5+8j

this v is complex number and in python a complex variable must use 'j' only for imaginary part

In [55]:
v

(5+8j)

In [56]:
v = 5+8i

SyntaxError: invalid decimal literal (1037632728.py, line 1)

as we can see if we use any other variable instead of 'j' we get an error

to get only imaginary or real component seperately we can use

In [61]:
v.real

5.0

In [60]:
v.imag

8.0

this is how we print real and imaginary parts of a complex variable seperately

to know functionality of a function or any feature in python click on the variable and press shift+tab

In [1]:
print("My name is xyz")

My name is xyz


Print function is used to display something on console, it is extensively used during initial days 
for now during debugging of program etc etc but once we get to know the concept of .logging and monitoring

In [76]:
s = "chatgpt"

In [77]:
type(s)

str

Now the question is to extract any given character (suppose 'p') from above string s = "pwskills"
ans - just like an array in C, "pwskills" is stored with indexing

char    Indexing(forward)   Indexing(backward)
p    -> 0                   -8
w    -> 1                   -7
s    -> 2                   -6
k    -> 3                   -5
i    -> 4                   -4
l    -> 5                   -3
l    -> 6                   -2
s    -> 7                   -1

this means a String is a collection of characters each stored at a different index value unlike integer, float etc in which complete number is treated an a single object and stored at same index value.

to get 'p' we use the notation --> s[0] or s[-1]
to get a sequence of characters (say 'pws' from "pwskills") we use --> s[0:3]

Syntax --> s[lower bound : upper bound : increment/decrement]  --> this is called "slicing" based on indexing.It will give you data 1 less than the upper bound that's why we add 1 to upper bound to get desired result.

note --> there is no index slicing in integer, float, bool etc.

Can I also do negative index slicing?
ans --> see below.

In [78]:
s[0]

'c'

In [79]:
s[2]

'a'

In [80]:
s[0:3]

'cha'

In Python, when using index slicing, the syntax s[start:end] includes elements starting from the start index up to, but not including, the end index. If the start index is greater than the end index, the slice will be empty.

In your case:

s = "chatgpt"
result = s[-1:-3]
print(result)

The output will be an empty string because the start index (-1) is greater than the end index (-3). In index slicing, Python adjusts the indices to make sense, and in this case, it results in an empty slice.

In [73]:
s[-1 : -3]

''

With the given string `s = "chatgpt"`, using the index slicing `s[-3:-1]` in Python means extracting the substring starting from the index -3 up to, but not including, the index -1.

Let's evaluate it:

s = "chatgpt"
result = s[-3:-1]
print(result)


The output will be:

'gp'

This is because the slice includes elements from the 3rd-to-last index (-3) up to the 2nd-to-last index (-1), which corresponds to the characters 'g' and 'p' in the string.

In [81]:
s[-3 : -1]

'gp'

now to use increment/decrement feature in index slicing 
let's say we want to print --> 'cagt' from "chatgpt"
i.e. at the gap of 1 so index starts from 0 ends at 7 with an increment of 2

note --> Bydefault index slicing is set to [lower bound = 0 : upper bound = (length-1) : increment = 1];

In [82]:
s[0:8:2]

'cagt'

In [83]:
s[::]

'chatgpt'

In [84]:
s[::2]

'cagt'

In [85]:
s[0:8:1]

'chatgpt'

In [86]:
s[2:4:2]

'a'

In [89]:
s[2:7:0]

ValueError: slice step cannot be zero

index slice step cannot be zero because then it means that there is no jump

in below example we get an empty string why so??
ans --> because we start from 2 and want to go till 7 so we need to increment to do so, but in below example we are trying to decrement our way to upper bound from lower bound which is conflicting in nature thatswhy we get an empty string.


In [90]:
s[2:7:-1]

''

in below also we are going from 7 to 0 so we need to decrement but instead we are incrementing so there will be conflict and there is no value present in forward(incremental) direction from the lowerbound mentioned in below slicing so we get empty(blank) string.

In [91]:
s[7:0]

''

In [92]:
s[8:0:-1]

'tpgtah'

In [93]:
s[-2:-8:1]

''

In [95]:
s[-2:-8:-1]

'pgtahc'

Q - print the whole string in reverse order
ans - to print in reverse order we can use any type of notation mentioned below

1) s[::-1]  -->  it starts calculation in reverse order so this literally means 
s[last index : first index : -1]

2) s[-1:-9:-1] or s[:-9:-1] --> this way we explicitly give index in reverse order to get reverse of string.

Note - for 2nd method we need to know upper and lower bound of string beforehand which is a disadvantage so we won't prefer method 2.


In [88]:
s[::-1]

'tpgtahc'

In [100]:
s[0:-9:-1]

'tpgtahc'

In [101]:
s[:-9:-1]

'tpgtahc'

Now some examples where the code can give error and some where it won't

in below we are searching for index 90 but we have only till index 7 so it gves error "string index out of bound" but in index slicing if we do the same thing as:

s[:90:] then it will start from 0 i.e. lower bound and it will move towards upper bound untill it reaches the end of string when upper bound is greater than length of string.

in simple words " in string slicing we never get 'index out of bound error'we get an empty string if we input conflicting limits. "

In [99]:
s[90]

IndexError: string index out of range

In [103]:
s[:90:]

'chatgpt'

In [104]:
s[:-90:-1]

'tpgtahc'

In [106]:
s[:-9000:-1]

'tpgtahc'

In [108]:
s1 = "this is my string class"

String has many inbuild available functions that can be used for String Manipulation.
here is a list:

1) Length of string
return number of characters in a string including spaces and special characters
len(string_name)

In [ ]:
len(s1)

2) finding a substring(set of characters) in string
string_name.find('xyz') --> return smallest index(among x,y,z) of first occurance of 'xyz' in s1 else returns -1

In [114]:
s1.find('s')

3

In [115]:
s1.find('x')

-1

below return address of 'i'

In [119]:
s1.find("ing")  

14

Don't memorize any function name because when we write "String_name." we get a list off all the functions available in string data type.

3) string_name.count('sub_string')
this method counts the number of occurances of a character or a substring inside a given string

In [120]:
s1.count('st')

1

4) string_name.upper() and s1.lower()
converts all the characters of string in uppercase and lowercase respectively.

In [121]:
s1.upper()

'THIS IS MY STRING CLASS'

In [124]:
s2 = "THIS IS MY STRING CLASS"

In [125]:
s2.lower()

'this is my string class'

5) string_name.title() 
this method is used to capitalize the first letter of all the words in given string i.e. it capitalize all the letters that are after a blank space plus the first character of string.

In [128]:
s1.title()

'This Is My String Class'

6) string_name.capitalize()
it capitalizes first character of string only

In [129]:
s1.capitalize()

'This is my string class'

7) addition --> + 
   and
   multiplication --> *
   are supported by strings

****** for concatenation operation both the values must have same datatype ******

like in below example we get an error because we try to concatenate string to an integer which is not possible if we do not use type casting which can be done as follows:
eg - s1 + 1

after type casting:
1) s1 + '1'
2) s1 + "1"
3) s1 + str(1)

but on concatenating 2 strings we do not get any error.

eg - "hello" + " world"

Now, on multiplying a string with an integer it repeats the string the number of times the value of that integer so for example

1) "sem4" * 3 --> sem4sem4sem4
2) "hello" *5 --> hellohellohellohellohello

but strings cannot be multiplied to other strings because it doesn't make any sense at all. so below code will give error

1) "hello" * "hello" --> error

Note - Substraction and Division are not supported in string because they do not make any sense in case of strings.

In [130]:
s1+1

TypeError: can only concatenate str (not "int") to str

In [131]:
s1 + "1"

'this is my string class1'

In [132]:
s1 + str(1)

'this is my string class1'

In [133]:
"hello" + " world"

'hello world'

In [134]:
"hello" * 5

'hellohellohellohellohello'

In [135]:
s1 * 2

'this is my string classthis is my string class'

In [136]:
(s1 + " ") * 2

'this is my string class this is my string class '

In [137]:
s1 / 2

TypeError: unsupported operand type(s) for /: 'str' and 'int'

In [138]:
s1 - 2

TypeError: unsupported operand type(s) for -: 'str' and 'int'

Note - in below example compiler is confused as to which part among --> 'I can' and 'I can't express how happy I am' has to considered a string because there is a single quote inside the string and the string is enclosed by single quotes only so it arises confusion for compiler to resolve this confusion use

1) double quotes for boundary if there are single quotes inside
"I can't express how happy I am"

2) or use single quotes for boundary if there are double quotes inside
'I can"t express how happy I am'


In [139]:
'I can't express how happy I am'

SyntaxError: unterminated string literal (detected at line 1) (1811489030.py, line 1)

In [140]:
"I can't express how happy I am"

"I can't express how happy I am"

In [141]:
'I can"t express how happy I am'

'I can"t express how happy I am'

Comments - in python to add info. or documentation of code for the reader to understand it better we use comments.

to add a single comment in python use '#' or '##' 

now to add multiline comment use triple single quotes OR use triple double quotes at the beginning and end of the lines.

In [3]:
# this is a single line comment

""" Comments - in python to add info. or documentation of code for the reader to understand it better we use comments.
to add a single comment in python use '#' or '##' now to add multiline comment use triple single quotes OR use triple double quotes at the beginning and end of the lines. """

" Comments - in python to add info. or documentation of code for the reader to understand it better we use comments.\nto add a single comment in python use '#' or '##' now to add multiline comment use triple single quotes OR use triple double quotes at the beginning and end of the lines. "

Lecture --> 99 (LIST DATATYPES)

List is a non primitive datatype in python that can store any type of data whether it's primitive or non primitive, list can store List inside it, tuple, objects etc.

In [2]:
l = [1, 345, 55, "sing", True, 5+7j, 345.667]  # a list can contain any type of data there is no restriction

To check data type of 'l' we use type()

In [7]:
type(l)

list

Accessing data from a list --> Using List Slicing

List also stores data in indexing order same as String data type and list also support backward or reverse indexing

data        Indexing(forward)   Indexing(backward)
1          -> 0                   -8
345        -> 1                   -7
55         -> 2                   -6
sing       -> 3                   -5
True       -> 4                   -4
5+7j       -> 5                   -3
345.667    -> 6                   -2

In [8]:
l[0]

1

In [9]:
l[6
]

345.667

In [12]:
l[-1]

345.667

as the length of list is 7 therefore there is no element at index 90 in fact there is no index 90 whatsoever.

In [10]:
l[90]

IndexError: list index out of range

But as we have already seen in string that String slicing never gives index out of range error same goes for list slicing

List Slicing:

In [11]:
l[:3]

[1, 345, 55]

Reverse a list:

In [13]:
l[::-1]

[345.667, (5+7j), True, 'sing', 55, 345, 1]

Extract data on even indices of list 'l'

In [14]:
l[::2]

[1, 55, True, 345.667]

Now trying to use list and string simultaneouly and trying to find differences

In [19]:
s = "college is hell"

In [16]:
l+s

TypeError: can only concatenate list (not "str") to list

from above error we understand that a list can be concatenated with other list but not with string

Now trying to Solve this:
approach --> convert string 's' to a list using type conversion or we can say passing string as an argument in list()
            
            Problem with above approach is that list() type conversion converts string 's' into a list by seperating each individual characters and then stores each character as a seperate entity i.e.

            s = "college is hell" will be broken down as shown below:

In [19]:
list(s)

['c', 'o', 'l', 'l', 'e', 'g', 'e', ' ', 'i', 's', ' ', 'h', 'e', 'l', 'l']

In [20]:
dummy = l;

In [21]:
dummy + list(s)

[1,
 345,
 55,
 'sing',
 True,
 (5+7j),
 345.667,
 'c',
 'o',
 'l',
 'l',
 'e',
 'g',
 'e',
 ' ',
 'i',
 's',
 ' ',
 'h',
 'e',
 'l',
 'l']

this defies our basic purpose of using type conversion, we want whole string 's' as a single character.

We have to do this using :
append() function or extend() function --> discussed later

Ques - given above list as : l = [1, 345, 55, "sing", True, 5+7j, 345.667] and we need to extract "si" from 3rd index "sing"?

steps:

1) first we need to write code to extract whole 3rd index element i.e "sing"

In [23]:
l[3]

'sing'

2) then we know that 'l[3]' means "sing" string so we can perform string slicing on 'l[3]'

In [22]:
l[3][:2]

'si'

Ques - given above list as : l = [1, 345, 55, "sing", True, 5+7j, 345.667] and we need to extract "Tr" from 4rd index "True"?

Steps:

1) first we need to extract True i.e. at 4th index

In [24]:
l[4]

True

In [25]:
type(l[4])

bool

2) now as this True is boolean as we can see above so we can simply typecast it to string or list to get tr (preferably string)

In [4]:
str(l[4])[:2]

'Tr'

In [6]:
print(l) #prints entire list

[1, 345, 55, 'sing', True, (5+7j), 345.667]


below will give error as 5 is integer type data

In [7]:
l + 5

TypeError: can only concatenate list (not "int") to list

if we somehow convert 5 to a list then we can add 5 to list also we can use append() and extend() methods 

but we can simply append list to another list using "+" operator

In [2]:
l1 = [3,4,5]

In [10]:
l1+l

[3, 4, 5, 1, 345, 55, 'sing', True, (5+7j), 345.667]

In [11]:
l+l1

[1, 345, 55, 'sing', True, (5+7j), 345.667, 3, 4, 5]

observation --> order of new string depends of whether we wrote "l+l1" or "l1+l"

Using "*" operator on list --> same as string
this way we append a copy of current list with the current list as shown below to get a new list.

In [12]:
l * 3

[1,
 345,
 55,
 'sing',
 True,
 (5+7j),
 345.667,
 1,
 345,
 55,
 'sing',
 True,
 (5+7j),
 345.667,
 1,
 345,
 55,
 'sing',
 True,
 (5+7j),
 345.667]

In [14]:
l1*3

[3, 4, 5, 3, 4, 5, 3, 4, 5]

Find number of elements in a List --> len() function

In [15]:
len(l)

7

USE OF --> append() fucntion to add anyhing to a list without explicit type casting

In [16]:
l #prints our list data

[1, 345, 55, 'sing', True, (5+7j), 345.667]

In [17]:
l.append(5) #adds the number 5 at the end of list 'l'

In [18]:
l

[1, 345, 55, 'sing', True, (5+7j), 345.667, 5]

now to add a string 's' we created previouly we can again use append method 

In [20]:
s

'college is hell'

In [21]:
l.append(s)  #adds string 's' as a single element of list 'l' at the end of list 'l'

In [22]:
l

[1, 345, 55, 'sing', True, (5+7j), 345.667, 5, 'college is hell']

In [23]:
l1

[3, 4, 5]

append() function can also be used to store a list inside another list as a single element as shown:

In [24]:
l.append(l1)

the list 'l' has become a nested list now.

In [25]:
l

[1, 345, 55, 'sing', True, (5+7j), 345.667, 5, 'college is hell', [3, 4, 5]]

Ques - if we have a list : l = [1, 345, 55, 'sing', True, (5+7j), 345.667, 5, 'college is hell', [3, 4, 5]], then extract element '4' which is an element of sublist of 'l' present at index 9 of 'l'?

Steps:

1) extract 9th index

In [26]:
l[9]

[3, 4, 5]

2) now as l[9] denotes sublist " [3, 4, 5] ", we can extract '4' easily using this sublist representation 'l[9]'

NOTE - we can simply use backward indexing to make above process easier by using l[-1] instead of l[9]

In [27]:
l[9][1]

4

USE OF --> extend() method

DESCRIPTION:-
(method) def extend(
    __iterable: Iterable,
    /
) -> None

Extend list by appending elements from the iterable.

MEANING OF ABOVE DESCRIPTION WILL BE DISCUSSED LATER.

for now --> iterable data means the data that can be iterated more than once using a loop or in other words a data that can be divided into indexes. Thatswhy 'int' data is not iterable whereas 'string' data is iterable.

In [30]:
l.extend(4)

TypeError: 'int' object is not iterable

In [32]:
l.extend("addthisbitch") #NOTE --> we cannot add SPACE in between text while appending a string to list

In [33]:
l

[1,
 345,
 55,
 'sing',
 True,
 (5+7j),
 345.667,
 5,
 'college is hell',
 [3, 4, 5],
 'a',
 'd',
 'd',
 't',
 'h',
 'i',
 's',
 'b',
 'i',
 't',
 'c',
 'h']

NOTE --> using extend our string is appended not as single entity of list rather extend() will unwrap it into individual characters and will then append each character as a seperate element of list.

now to extend a list into another list we use the following:

In [34]:
l.extend([3,4,5])

In [35]:
l

[1,
 345,
 55,
 'sing',
 True,
 (5+7j),
 345.667,
 5,
 'college is hell',
 [3, 4, 5],
 'a',
 'd',
 'd',
 't',
 'h',
 'i',
 's',
 'b',
 'i',
 't',
 'c',
 'h',
 3,
 4,
 5]

while appending list to a list we again see same result as with string that each element is unwrapped into single character units which will be appended in the list with each of it's element inserted as seperate entity.

Ques - append and extend functions insert data at the end of list so is there any method using which we can insert data at first position or at any given index??
Ans - Yes, and that function is 'insert(index, object)' where object will be inserted at index and shift list forward by 1

DESCRIPTION
(__index: SupportsIndex, __object: Any, /) -> None
Insert object before index.

In [36]:
l.insert(1, "shami")

In [37]:
l

[1,
 'shami',
 345,
 55,
 'sing',
 True,
 (5+7j),
 345.667,
 5,
 'college is hell',
 [3, 4, 5],
 'a',
 'd',
 'd',
 't',
 'h',
 'i',
 's',
 'b',
 'i',
 't',
 'c',
 'h',
 3,
 4,
 5]

Now trying to insert a list in list 'l' at index 5

In [39]:
l.insert(5, [7,8,9])

In [40]:
l

[1,
 'shami',
 345,
 55,
 'sing',
 [7, 8, 9],
 True,
 (5+7j),
 345.667,
 5,
 'college is hell',
 [3, 4, 5],
 'a',
 'd',
 'd',
 't',
 'h',
 'i',
 's',
 'b',
 'i',
 't',
 'c',
 'h',
 3,
 4,
 5]

question --> DESCRIPTION of insert() function in python:

(__index: SupportsIndex, __object: Any, /) -> None
Insert object before index.

what is meaning of  '/' present after object??

ChatGPT

In the function signature you provided:

python

insert(__index: SupportsIndex, __object: Any, /) -> None

The / symbol in Python function signatures is used to indicate that the parameters listed before it are positional-only, meaning they must be specified by position and cannot be specified by keyword.

In this case, __index and __object are positional-only parameters. When calling the insert function, you would provide values for these parameters in the order they appear in the function signature.

For example:

python

my_list = [1, 2, 3]
my_list.insert(1, 4)

In this example, 1 is the value for __index (the index before which the object should be inserted), and 4 is the value for __object (the object to be inserted). The order of the arguments matters because of the positional-only nature of these parameters.

Note that the / symbol itself is not an operator; it's just a syntax feature in function signatures to specify positional-only parameters. It helps make the function call syntax more explicit and can be useful for API design.

In [47]:
l1.insert(-1, 45)

expectated output --> [3, 4, 5, 45]
but
result --> [3, 4, 45, 5]

this is a bit confusing but our expectation was illogical as we know that it will insert the element at mentioned index but it will also shift the elements after that index forward by 1 position. so the output is perfectly logical.

In [48]:
l1

[3, 4, 45, 5]

In [4]:
l1.insert(0, 45)

In [5]:
l1

[45, 3, 4, 5]

In [23]:
l1.append([2,3,4,5]);

In [7]:
l1

[45, 3, 4, 5, [2, 3, 4, 5]]

In [21]:
l1.insert(2,'sudh')

In [9]:
l1

[45, 3, 'sudh', 4, 5, [2, 3, 4, 5]]

In [10]:
l1.pop()

[2, 3, 4, 5]

In [12]:
l1.append(5)

In [13]:
l1.pop()

5

In [14]:
l1.pop(2) #removes data at index 2

'sudh'

In [15]:
l1

[45, 3, 4, 5, [2, 3, 4, 5]]

l1.remove(x) will delete first occurance of value x if it is present inside l1.
difference between pop and remove is that pop will always go with indexes but remove will delete actual value also pop will return the deleted value whereas remove will not.

In [16]:
l1.remove(3)

In [17]:
l1

[45, 4, 5, [2, 3, 4, 5]]

In [18]:
l1.remove(2345)

ValueError: list.remove(x): x not in list

to remove data from the list present inside l1 list we do:
i.e in l1 remove() element 3 from list present in l1 which is [45, 4, 5, [2, 3, 4, 5]]

In [24]:
l1[-1].remove(3)

In [25]:
l1

[45, 4, 'sudh', 5, [2, 4, 5], [2, 4, 5]]

now how can we remove 'dh' from 'sudh' present inside l1,
how to remove a part of string present inside a list

In [27]:
l1[2].remove(2)

AttributeError: 'str' object has no attribute 'remove'

since remove is not a method of string class therefore we cannot call remove method using string object.

q - how to remove second occurance of an element in a list using remove() only?
ans - it cannot be done directly on list because remove deletes first occurance of it's argument from list.
we can remove last occurence as well by first getting reverse of the list then remove(x)

In [35]:
l1[::-1]

[[2, 4, 5], [2, 4, 5], 5, 'sudh', 4, 45]

using list slicing to reverse a list will just print reverse of that list, it will not affect the original list.
to reverse elements in original list we can do 2 things:
l1 = l1.[::-1]
l1.reverse()

In [36]:
l1

[45, 4, 'sudh', 5, [2, 4, 5], [2, 4, 5]]

In [37]:
l1.reverse()

In [38]:
l1

[[2, 4, 5], [2, 4, 5], 5, 'sudh', 4, 45]

there is also a method available in list which is 'sort()', it arrange elemtns in ascending and descending order, but the elements of the list should not contain 

In [4]:
ls = [45,23,90,0,3,4,5,1,7,8,9.35,34.657564533]

In [5]:
ls.sort()

In [6]:
ls

[0, 1, 3, 4, 5, 7, 8, 9.35, 23, 34.657564533, 45, 90]

(method) def sort(
    *,
    key: None = None,
    reverse: bool = False //false indicates ascending order sorting
) -> None


to sort elements in descending order we do:
(method) def sort(
    *,
    key: None = None,
    reverse: bool = True //we make it True
) -> None


In [7]:
ls.sort(reverse=True)

In [8]:
ls

[90, 45, 34.657564533, 23, 9.35, 8, 7, 5, 4, 3, 1, 0]

In [9]:
ls1 = [[2, 4, 5], [2, 4, 5], 5, 'sudh', 4, 45]

In [10]:
ls1.index('sudh') #it return the index of the parameter inside list.

3

In [11]:
ls1.count('sudh') #counts number of occurence of parameter inside list

1

In [13]:
s = "sudh"

In [12]:
ls2 = [3,4,5,6]

In [14]:
s[0] = 'a'; #immutable string

TypeError: 'str' object does not support item assignment

In [15]:
ls2[0] = 30 #list is mutable

In [16]:
ls2

[30, 4, 5, 6]

mutability means that we can add, delete or replace an element at any index of an object.
list objects are mutable
string objects are immutable

In [17]:
s.replace('s', 'a')

'audh'

above replace method creates a new object in which 's' is replace by 'a' but the original object is unaffected.

In [19]:
s #see that 's' string is unaffected

'sudh'

TUPLE - tuple is exactly same as list but tuple is immutable.

tuple can also contain any type of data

In [21]:
t = ([2, 4, 5], 5, 'newton', True, 1+2j, 3.14, 'e', (2,3,4.56,False))

In [22]:
t

([2, 4, 5], 5, 'newton', True, (1+2j), 3.14, 'e', (2, 3, 4.56, False))

In [23]:
type(t)

tuple

In [24]:
len(t)

8

In [25]:
t[0]

[2, 4, 5]

In [26]:
t[-1]

(2, 3, 4.56, False)

In [31]:
t[::-1]

((2, 3, 4.56, False), 'e', 3.14, (1+2j), True, 'newton', 5, [2, 4, 5])

In [32]:
ls3 = [[2, 4, 5], 5, 'newton', True, (1+2j), 3.14, 'e', (2, 3, 4.56, False)]

In [33]:
t[0] = 53

TypeError: 'tuple' object does not support item assignment

but,

In [34]:
ls3[0] = 53

In [35]:
ls3

[53, 5, 'newton', True, (1+2j), 3.14, 'e', (2, 3, 4.56, False)]

tuples are used to store data which shouldn't be overwritten.
there are only 2 functions in tuple

t.count(x) --> counts number of occurence of x in t
t.index(x) --> rreturn index of x in t

In [37]:
t.count(5) #5 occurs 3 times inside t

1

In [38]:
t.count(50)

0

In [39]:
t.index(True) #True is present at index 3

3

SET --> collection same as list, tuple etc

when set is initialized by {} "empty curly braces" then it's type is assumed as "dictionary" by compiler, but if we enter some values in it like:

s2 = {2,3,4,55,6} then it's type is assumed as set by compiler.

How set is different from list and tuple?
set can only contain immutable objects and primitive elements to maintain hashability of the set.
hashability --> https://chat.openai.com/share/4cab4cec-a7ba-44f4-815b-290e8ecef898

In [40]:
s1 = {} 

In [41]:
type(s1)

dict

In [42]:
s2 = {2,3,4,55,6}

In [43]:
type(s2)

set

In [44]:
s3 = {324, 456, 456, "sudh", 45+45j, 34.465, (3,4,5)} #can keep immutable objects

In [45]:
s3 = {324, 456, 456, "sudh", 45+45j, 34.465, [3,4,5]} #can keep mutable objects

TypeError: unhashable type: 'list'

TypeError:unhashable type: 'list' --> https://chat.openai.com/share/4cab4cec-a7ba-44f4-815b-290e8ecef898

why do we use set in python?
set only stores unique data just like set in mathematics. uppercase and lowercase are treated as different data.
set stores data in unordered way.

In [49]:
s4 = {2,3,4,5,6,2,2,3,4,5,2,3,1,2,3,4,5,6,1,2,2,'sudh','Sudh'}

In [50]:
s4

{1, 2, 3, 4, 5, 6, 'Sudh', 'sudh'}

In [51]:
ls4 = [2,3,4,5,6,2,2,3,4,5,2,3,1,2,3,4,5,6,1,2,2,'sudh','Sudh'] #list

In [52]:
ls4

[2, 3, 4, 5, 6, 2, 2, 3, 4, 5, 2, 3, 1, 2, 3, 4, 5, 6, 1, 2, 2, 'sudh', 'Sudh']

to remove all the duplicate data from list ls4 we can simply:
1) typecast list to set
    ls4 = set(ls4)
2) typecast it again
    ls4 = list(ls4)

can do this in one step using
    ls4 = list(set(ls4))

In [53]:
 ls4 = set(ls4)    

In [55]:
ls4 #it bacame set due to typecasting

{1, 2, 3, 4, 5, 6, 'Sudh', 'sudh'}

In [56]:
ls4 = list(ls4)

In [58]:
ls4 #it again became list due to type casting

[1, 2, 3, 4, 5, 6, 'Sudh', 'sudh']

In [59]:
ls4 = list(set(ls4))

In [60]:
ls4

[1, 2, 3, 4, 5, 6, 'Sudh', 'sudh']

In [61]:
s5 = {234,45,23,12,567,45,2,789,234,"abc",456,342,23}

In [62]:
s5

{12, 2, 23, 234, 342, 45, 456, 567, 789, 'abc'}

NOTE - set doesn't support indexing and slicing operations.

In [63]:
s5[0]

TypeError: 'set' object is not subscriptable

In [64]:
s5[::-1]

TypeError: 'set' object is not subscriptable

In [66]:
s5.add() #this adds data at random position depending on it's hashing function working in background.

#This has no effect if the element is already present.

(method) def add(
    __element: Any,
    /
) -> None

Add an element to a set.
This has no effect if the element is already present.

In [67]:
s5 

{12, 2, 23, 234, 342, 4, 45, 456, 567, 789, 'abc'}

In [69]:
s5.remove(4) #will remove 4 if it is present in s5 set else it will give error.

DICTIONARY
just like a real dictionary we have a word and meaning pair
similarly here we have a key:value pair

In [70]:
d={}

In [71]:
type(d)

dict

by default {} type --> dictionary 
1) if put linear data in {} --> set
2) if put key:value pair in {} --> dictionary

In [72]:
d1 = {'key' : "value"}

GUIDELINES FOR KEY:
1) key should be always unique (if not unique, key will update to last updated value assigned to it)
2) 

In [73]:
d2 = {'name' : "jin", "email" : "abc@gmail.com", "number" : 34535}

In [74]:
d2

{'name': 'jin', 'email': 'abc@gmail.com', 'number': 34535}

In [75]:
d3 = {234 : "sudh"}

In [76]:
d4 = {234 : "sudh", @_wer : "vlue"}

SyntaxError: invalid syntax (852085659.py, line 1)

In [77]:
d5 = {234 : "sudh", "@_wer" : "vlue"}

In [78]:
d6 = {234 : "sudh", wer : "vlue"}

NameError: name 'wer' is not defined

In [79]:
d7 = {234 : "sudh", True : 23454, False : 32453, 2.34 : "sudh"}

to extract values from a dictionary we use their correcponding keys.

In [81]:
d7[234]

'sudh'

In [82]:
d7[True]

23454

In [83]:
d7[1] #internally True  --> 1 and 
                 #False --> 0

23454

In [87]:
d8 = {'name' : "sudh", 'mail_id' : "ss@gmail.com", "name" : "newton"} #the value of key 'name' is updated from "sudh" to "newton".

In [90]:
d8['name']

'newton'

In [91]:
d9 = {'company' : 'udemy', "course" : ["C++", "python", "kotlin"]}

In [92]:
d9['course']

['C++', 'python', 'kotlin']

In [93]:
d9['course'][2]

'kotlin'

in place of VALUE we can pass any kind of data or collection i.e. VALUE can be a primitive data, list, string, tuple, dictionary, set etc.

In [95]:
d10 = {'number': [2,34,3,34,34], "assignment": (1,2,3,4,5,6), "launch_date": {28,12,14}, "class_time": {'C++': '1 pm', 'python': '3 pm', 'java': '7 pm'}}

In [96]:
d10

{'number': [2, 34, 3, 34, 34],
 'assignment': (1, 2, 3, 4, 5, 6),
 'launch_date': {12, 14, 28},
 'class_time': {'C++': '1 pm', 'python': '3 pm', 'java': '7 pm'}}

Q - extract '7 pm' from dictionary d10?


In [97]:
d10['class_time']['java']

'7 pm'

Q - add a new key in existing dictionary?
in below key is added at the end of dictionary

In [99]:
d10['mentor'] = ('newton', 'einstein', 'euclid')

In [100]:
d10

{'number': [2, 34, 3, 34, 34],
 'assignment': (1, 2, 3, 4, 5, 6),
 'launch_date': {12, 14, 28},
 'class_time': {'C++': '1 pm', 'python': '3 pm', 'java': '7 pm'},
 'mentor': ('newton', 'einstein', 'euclid')}

Q - to delete a key from a dictionary?

In [101]:
del d10['mentor']

Q - Extract keys from a dictionary?

In [102]:
d10.keys()

dict_keys(['number', 'assignment', 'launch_date', 'class_time'])

In [104]:
list(d10.keys()) #typecast keys to list, we can typecast in any type of collection(eg. tuple, set etc)

['number', 'assignment', 'launch_date', 'class_time']

In [103]:
d10.values()

dict_values([[2, 34, 3, 34, 34], (1, 2, 3, 4, 5, 6), {28, 12, 14}, {'C++': '1 pm', 'python': '3 pm', 'java': '7 pm'}])

In [105]:
list(d10.values()) #typecast values to list, we can typecast in any type of collection(eg. tuple, set etc).

[[2, 34, 3, 34, 34],
 (1, 2, 3, 4, 5, 6),
 {12, 14, 28},
 {'C++': '1 pm', 'python': '3 pm', 'java': '7 pm'}]

In [109]:
tuple(d10.values())

([2, 34, 3, 34, 34],
 (1, 2, 3, 4, 5, 6),
 {12, 14, 28},
 {'C++': '1 pm', 'python': '3 pm', 'java': '7 pm'})

Q - Extract key:value pairs from dictionary?

In [110]:
d10.items()

dict_items([('number', [2, 34, 3, 34, 34]), ('assignment', (1, 2, 3, 4, 5, 6)), ('launch_date', {28, 12, 14}), ('class_time', {'C++': '1 pm', 'python': '3 pm', 'java': '7 pm'})])

In [112]:
list(d10.items()) #can be typecasted to any datatype (eg - list here)

[('number', [2, 34, 3, 34, 34]),
 ('assignment', (1, 2, 3, 4, 5, 6)),
 ('launch_date', {12, 14, 28}),
 ('class_time', {'C++': '1 pm', 'python': '3 pm', 'java': '7 pm'})]

Q - update value of a key?

In [113]:
d10['test key'] = "test value"

In [114]:
d10

{'number': [2, 34, 3, 34, 34],
 'assignment': (1, 2, 3, 4, 5, 6),
 'launch_date': {12, 14, 28},
 'class_time': {'C++': '1 pm', 'python': '3 pm', 'java': '7 pm'},
 'test key': 'test value'}

In [115]:
d10['test key'] = 'new value'

In [116]:
d10

{'number': [2, 34, 3, 34, 34],
 'assignment': (1, 2, 3, 4, 5, 6),
 'launch_date': {12, 14, 28},
 'class_time': {'C++': '1 pm', 'python': '3 pm', 'java': '7 pm'},
 'test key': 'new value'}

Q - How to remove a key:value pair?
ans - use pop method
        remove specified key and return the corresponding value.

        If the key is not found, return the default if given; otherwise, raise a KeyError.
        (TypeError: pop expected at least 1 argument, got 0)

In [118]:
d10.pop('assignment')

(1, 2, 3, 4, 5, 6)

In [119]:
d10

{'number': [2, 34, 3, 34, 34],
 'launch_date': {12, 14, 28},
 'class_time': {'C++': '1 pm', 'python': '3 pm', 'java': '7 pm'},
 'test key': 'new value'}

In [121]:
d10.pop()

TypeError: pop expected at least 1 argument, got 0